### ISSUE TITLE
add metadata (license ...)

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#1]
as discussed today, starting with the metadata in a new repository (LICENSE, gitignore etc) is a reasonable first step/commit

**Comment by svenbioinf** [comment]
Yes, this is what function "clone()" does. It copies all metadatafiles in a new empty directory.

**Comment by ptrebert** [comment]
yes, but >this< repository itself obviously also needs to be populated with the metadata files

**Comment by svenbioinf** [comment]
Alright got you. I added meta files, however we should talk about how to edit them for this repository.

**Comment by ptrebert** [comment]
- restructure pyproject with namespace `cubi.devtools.script`
- remove tomls subfolder

**Comment by svenbioinf** [comment]
updated pyproject like discussed yesterday
removed tomls subfolder

**Comment by ptrebert** [comment]
ok
