### ISSUE TITLE
never check boolean condition like that

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#10]
Here, it is even unclear to me what the True/False conditions are that you are trying to check:

https://github.com/core-unit-bioinformatics/devtools/blob/9ff4c5aad8a1aa98750472d4a9746560fc3951b6/update_template.py#L13

```python
if any([list of bools]):
    # case: at least one is true
else:
    # case: all are false
```

```python
if all([list of bools]):
    # case: all are true
else:
    # case: at least one is false
    # I guess you wanted this case
```

Even in R, writing something like
```R
if (expression = TRUE) {
    # do something
}
```
is not idiomatic afaik.

Regarding such comparisons, also take note of the Pep8 Programming Recommendations for comparing to `None`:

> Comparisons to singletons like None should always be done with `is` or `is not`, never the equality operators.
> 
> Also, beware of writing `if x` when you really mean `if x is not None` – e.g. when testing whether a variable or
> argument that defaults to None was set to some other value. The other value might have a type
> (such as a container) that could be false in a boolean context!

**Comment by svenbioinf** [comment]
updated
