### ISSUE TITLE
shorter functions / split functionality

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#11]
The `update_file` function is almost too long to be displayed w/o scrolling (in landscape mode ...). This is often a sign that the function does too much in its own body, and that functionality should be moved into separate "more specialized" functions (= separation of concerns; one function should do one job).

https://github.com/core-unit-bioinformatics/devtools/blob/ab539f8b135350189a99627fbf45229df0297c01/update_template.py#L76

Reading the function body, there are at least 3 somewhat independent actions: (i) compute/get git sha checksums; (ii) compare and get user input if necessary; (iii) perform the actual update.

Another indicator that something is skewed in the control flow: you end up at `print("Nothing to update.")` with two different `if/else` checks. Logically, this can only be the result of "no files changed". Another possibility would be that there is something to update, but the user decides to skip the update.

**Comment by svenbioinf** [comment]
Put checksum generation in dedicated functions.
The update function is now more compact.

I dont get the second part of your comment. What's so bad about two if/else checks?

**Comment by ptrebert** [comment]
I think I explained this f2f in detail - since this is a general comment about proper design, I'll close the issue for now.
