### ISSUE TITLE
several comments: logic, scope of function, python idioms

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#18]
I have a few comments about this function:

1. in general, the scope is too restrictive; why can't there be other external workflows besides nextflow? See the Varlociraptor workflow already forked. The command line switch should simply be something like `--external` and the script also simply check if a `cubi/` subfolder exists.
2. the comparison operator is `not in` and not `not ... in`, see [Pep8 programming recommendations](https://peps.python.org/pep-0008/#programming-recommendations)
3. the `if/else` or rather `elif/elif` below checks a binary `true/false` condition, i.e. there are exactly two options. The code below checks if the condition is true, and if it is not, the code checks if the condition is false, which is a logical must.

https://github.com/core-unit-bioinformatics/devtools/blob/0393e1701100d6c307d339253cad21f3a051d0ed/update_template.py#L71-L80

**Comment by svenbioinf** [comment]
Regarding 1), Yes I can make it more general and yes by manual setting --external, the script knows what to do. However it would be great if the tool would detect this automatically. "Simply check if cubi folder exists" - That ofc only works for an already established workflow/ folder structure. Imagine starting from an empty directory- there is no "cubi" folder. Therefore the script scans the workflow name to guess if its an external one. Sadly our workflow name definition does not inlcude an external tag. So its difficult to implement a solution for the script to know whether to create a cubi folder or put metadata files on the first level. If we dont find an automatic solution, I"ll make --external as a mandatory parameter
2)fixed
3) still open

**Comment by svenbioinf** [comment]
Regarding 1) again: deactivated automatic external workflow detection. Needs now to be set manually with --external. I dont see a way for the script to detect an external workflow from the foldername of an empty folder.
