### ISSUE TITLE
explicit checks makes this more readable

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#19]
okay-ish because it's still short, but simply calling the dedicated functions of the ArgumentParser makes this much clearer:

```python
if len(sys.argv) == 1:
    parser.print_help()
    parser.exit()  # default is code 0
args = parser.parse_args()
return args
```

https://github.com/core-unit-bioinformatics/devtools/blob/0393e1701100d6c307d339253cad21f3a051d0ed/update_template.py#L67

**Comment by svenbioinf** [comment]
made more readable
