### ISSUE TITLE
keep args in the scope

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#2]
It's common to return `args` and then access attributes as needed in subsequent lines (necessary as soon as more than 1 argument is passed via the cli)

https://github.com/core-unit-bioinformatics/devtools/blob/4302a211efca8e387a338d80581a9dd139b2dcee/update_template.py#L7

**Comment by svenbioinf** [comment]
updated

**Comment by ptrebert** [comment]
I'll mark this as resolved. Assigning the members of `args.` to identically named variables in a scope of ~10 lines with a single access to the respective member seems a bit ... over the top ;-)
