### ISSUE TITLE
f-string formatting

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#3]
Just to mention this early, recommended string formatting in Python3 uses so-called f-strings

https://github.com/core-unit-bioinformatics/devtools/blob/4302a211efca8e387a338d80581a9dd139b2dcee/update_template.py#L8

So the above line is fine but could be rewritten as:
```python
print(f"Project directory set as: {project_dir}")
```

**Comment by svenbioinf** [comment]
updated
