### ISSUE TITLE
variable naming / pathlib module

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#4]
See Pep8, variable names in Python should not be CamelCase (I think this is more common in R?). Also, naming variables after their type (`...List`) is discouraged because the type may change at some point and it does not say anything about what this object (the list here) actually contains / why it is needed etc; in other words, it doesn't help understanding the code beyond the syntactical level

https://github.com/core-unit-bioinformatics/devtools/blob/4302a211efca8e387a338d80581a9dd139b2dcee/update_template.py#L10

Another point, for path operations like `path.join` or `listdir`, Python's `pathlib` module is much better suited because it offers many more convenient shortcuts compared to `os.path`

**Comment by svenbioinf** [comment]
updated
