### ISSUE TITLE
use list comprehension

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#5]
Since `updateFile` (naming!) does not return anything that you want to retain, the more idiomatic way would be a list comprehension ...

https://github.com/core-unit-bioinformatics/devtools/blob/4302a211efca8e387a338d80581a9dd139b2dcee/update_template.py#L18-L19

...like this
```python
[updateFile(f, project_dir) for f in filesToUpdate]
```

Note regarding naming: `filesToUpdate` is a much more informative name than `fileList`

**Comment by svenbioinf** [comment]
updated
