### ISSUE TITLE
more flexibility, limited by defaults

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#7]
Hard-coded data like that limit flexibility (require more substantial changes later). The same effect can be realized by making this a cli parameter that is set to the most common default.

https://github.com/core-unit-bioinformatics/devtools/blob/4302a211efca8e387a338d80581a9dd139b2dcee/update_template.py#L24

**Comment by svenbioinf** [comment]
updated

**Comment by ptrebert** [comment]
and what about the other cases that are just like this one and that are still in the code?

**Comment by svenbioinf** [comment]
all fixed now.
