### ISSUE TITLE
code formatting: editorconfig (metadata) + black

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#8]
This line is too long, which means the code was not formatted with black before committing (other parts of the script give that away, too, but line length is obvious ;-) )

https://github.com/core-unit-bioinformatics/devtools/blob/4302a211efca8e387a338d80581a9dd139b2dcee/update_template.py#L44

**Comment by svenbioinf** [comment]
updated with spyder internal black implementation. Is that better?

**Comment by ptrebert** [comment]
The point of housekeeping tools such as black is that they tell you if your code needs to be changed or not. If black has nothing more to say, then that's it. Same for pylint, by the way. Since the repo still does not have the additional metadata files (in this case: the `.editorconfig` setting the parameters for black), I can't tell if that differs from Spyder's black version or not; Spyder would also honor an `.editorconfig` if present, I presume. I close this with reservation.
