### ISSUE TITLE
"try to be nice with user input"

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/devtools#9]
Here, the user can give exactly one answer that means "yes", i.e. "y", and anything else means "no", no matter the exact input (within certain boundaries). That is asking a lot of attention from the user - and when they type "yes", should that lead to a "no"?

https://github.com/core-unit-bioinformatics/devtools/blob/4302a211efca8e387a338d80581a9dd139b2dcee/update_template.py#L52

When it comes to user input and the user interface, there is often not a perfect answer, unfortunately. What I would do for cases like that is using a mapping that allows for some flexibility and makes it clear if the user provided reasonable input at all (here, the question is simple, but they may misunderstand more complex queries...). Example:

```python
answers = {
    "yes": True,
    "y": True,
    "yay": True,
    "no": False,
    "n": False,
    "nay": False
}
user_response = input('Update?: (y/n)')  # remark: update what?
try:
    do_update = answers[user_response]
except KeyError:
    raise ValueError(f"That was a yes or no question, but you answered: {user_response}")

if do_update:
    ...

**Comment by svenbioinf** [comment]
updated
